/**
 * Summary.
 *
 * Description. A layout is UI that is shared between routes. 
 *
 * @link https://nextjs.org/docs/app/api-reference/file-conventions/layout
 */

import '@/styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
